<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDgfgEEz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDgfgEEz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDgfgEEz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDgfgEEz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDgfgEEz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DgfgEEz',
    'container.build_id' => '9a5f6c39',
    'container.build_time' => 1617582443,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDgfgEEz');
